routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@show');

Route::get('home', 'HomeController@show');

Route::resource("leads", 'LeadController');
Route::resource("lead_status", "LeadStatusController");
Route::resource("lead_forms", "LeadFormController");
Route::resource("lead_form_fields", "LeadFormFieldController");
Route::resource("field_values", "FieldValueController");

Route::get('render/form/{form}', 'FormRenderController@view');
Route::get('render/field/{type}', 'FormFieldRenderController@view');

Route::get('email/submission/{submission}', 'SendEmailsController@sendSubmission');
Route::post('leadform/settings/{form}', 'FormSettingsController@view');

Route::get('shopify', 'ShopifyController@index');
Route::get('shopify/register', 'ShopifyOAuthController@register');
Route::get('shopify/start_auth', 'ShopifyOAuthController@startAuth');
Route::get('shopify/authorise', 'ShopifyOAuthController@authorise');
Route::get('shopify/settings', 'ShopifyController@settings');
Route::get('shopify/help', 'ShopifyController@help');

app/Lead.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
  use HasTeamScope;

  public static function existingLead($email, LeadForm $form){
    $existing = self::where([
      'email' => $email,
      'lead_form_id' => $form->id,
      ])->first();

    if(!$existing){
      $existing = new self();
      $existing->email = $email;
      $existing->lead_form_id = $form->id;
      $existing->team_id = $form->team_id;
      $existing->save();
    }

    return $existing;
  }

  public function status(){
    return $this->belongsTo(LeadStatus::class);
  }

  public function leadForm(){
    return $this->belongsTo(LeadForm::class);
  }

  public function form(){
    return $this->leadForm()->first();
  }

  public function submissions(){
    return $this->hasMany(Submission::class);
  }
  public function values(){
    return $this->hasManyThrough(FieldValue::class, Submission::class);
  }

  public function teamSubmissions(){
    return $this->submissions()->team()->get();
  }

  public function getDisplayDateAttribute($value){
    return $this->created_at->toDayDateTimeString();
  }

  public function path(){
    return url("leads/{$this->id}");
  }
  public function fields(){
    return $this->form()->fields->sortBy('weight')->filter(function($field){
      $doNotDisplayFields = ['submit', 'email'];
      return !in_array($field->field_type, $doNotDisplayFields);
    });
  }
}

resources/views/error.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <p>There were some problems with your input.</p>
        <ul>
            @foreach ($errors->all() as $error)
                <li><i class="glyphicon glyphicon-remove"></i> {{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/home.blade.php
@extends('spark::layouts.app')

@section('content')
<home :user="user" inline-template>
  <div class="container">
    <!-- Application Dashboard -->
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">AutoCoda Leads Generator</div>
          <div class="panel-body">
            Welcome to AutoCoda Leads Generator where we keep all leads in one convenient place!
          </div>
        </div>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">Leads</div>
          <div class="panel-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Email</th>
                  <th>Form</th>
                  {{-- <th>Enquiry</th> --}}
                  <th>Submission Date</th>
                </tr>
              </thead>
              <tbody>
                @if(count($leads))
                @foreach ($leads as $lead)
                <tr>
                  <td><a href="{{ $lead->path() }}">{{ $lead->email }}</a></td>
                  <td>{{ $lead->form()->title }}</td>
                  {{-- <td><a href="{{ $lead->path() }}">{{ $lead->enquiry_short }}</a></td> --}}
                  <td>{{ $lead->display_date }}</td>
                </tr>
                @endforeach
                @else
                <tr>
                <td colspan=4 class="text-center">There are no leads yet.</td>
                </tr>
                @endif
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">Lead Forms</div>
          <div class="panel-body">
            <table class="table">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Description</th>
                  <th>Last Updated</th>
                </tr>
              </thead>
              <tbody>
                @if(count($leadforms))
                @foreach ($leadforms as $form)
                <tr>
                  <td><a href="{{ $form->path() }}">{{ $form->title }}</a></td>
                  <td>{{ $form->description }}</td>
                  <td>{{ $form->display_date }}</td>
                </tr>
                @endforeach
                @else
                <tr>
                  <td colspan=3 class="text-center">You have no forms. <a href="{{ url('lead_forms/create')}}">Make one here</a>.</td>
                </tr>
                @endif
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</home>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Starter Template</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="starter-template.css" rel="stylesheet"> -->


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    @yield('css')
</head>

<body>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        @yield('header')
        @yield('content')
    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script> -->
    @yield('scripts')
</body>
</html>