routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@show');

Route::get('home', 'HomeController@show');

Route::resource("leads", 'LeadController');
Route::resource("lead_status", "LeadStatusController");
Route::resource("lead_forms", "LeadFormController");
Route::resource("lead_form_fields", "LeadFormFieldController");
Route::resource("field_values", "FieldValueController");

Route::get('render/form/{form}', 'FormRenderController@view');
Route::get('render/field/{type}', 'FormFieldRenderController@view');

Route::get('email/submission/{submission}', 'SendEmailsController@sendSubmission');
Route::post('leadform/settings/{form}', 'FormSettingsController@view');

Route::get('shopify', 'ShopifyController@index');
Route::get('shopify/register', 'ShopifyOAuthController@register');
Route::get('shopify/start_auth', 'ShopifyOAuthController@startAuth');
Route::get('shopify/authorise', 'ShopifyOAuthController@authorise');
Route::get('shopify/settings', 'ShopifyController@settings');
Route::get('shopify/help', 'ShopifyController@help');

app/Http/Controllers/LeadFormController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\LeadForm;
use App\LeadFormField;
use Illuminate\Http\Request;

class LeadFormController extends Controller {

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
    $this->middleware('auth');
  }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $lead_forms = LeadForm::team()->orderBy('id', 'desc')->paginate(10);

    return view('lead_forms.index', compact('lead_forms'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Response
   */
  public function create()
  {
    $fields = $this->getFormFields();

    return view('lead_forms.create', compact('fields'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param Request $request
   * @return Response
   */
  public function store(Request $request)
  {
    $lead_form = new LeadForm($request->all());
    $lead_form->save();
    $lead_form->saveFields($request->fields);

    return redirect()->route('lead_forms.index')->with('message', 'Form created successfully.');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $lead_form = LeadForm::findOrFail($id);

    return view('lead_forms.show', compact('lead_form'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $lead_form = LeadForm::with('fields')->findOrFail($id);
    $fields = $this->getFormFields();

    return view('lead_forms.edit', compact('lead_form', 'fields'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @param Request $request
   * @return Response
   */
  public function update(Request $request, $id)
  {
    $lead_form = LeadForm::findOrFail($id);
    $lead_form->saveFields($request->fields);
    $lead_form->fill($request->all())->save();

    return redirect()->route('lead_forms.index')->with('message', 'Form updated successfully.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    $lead_form = LeadForm::findOrFail($id);

    if(count($lead_form->leads)){
      return back()->with('error', 'Unable to delete form, you have leads attached to this form. Please remove them first.');
    }

    $lead_form->delete();

    return redirect()->route('lead_forms.index')->with('message', 'Form deleted successfully.');
  }

  protected function getFormFields(){
    return LeadFormField::team()->get()->filter(function($field){
      return $field->field_type != 'page_referer';
    });
  }

}

resources/views/lead_forms/create.blade.php
@extends('spark::layouts.app-inner')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
  <h1><i class="glyphicon glyphicon-plus"></i> Create a new Lead Form</h1>
</div>
@endsection

@section('content')
@include('error')

<div class="row">
  <div class="col-md-12">
    @if(!count($fields))
    <div class="panel panel-warning">
      <div class="panel-heading">No form fields available.</div>
      <div class="panel-body">
       You cannot save a form without any fields.
       <a href="{{ url('lead_form_fields/create') }}">Create some here.</a>
     </div>
   </div>
   <span> </span>
   @endif

   <form action="{{ route('lead_forms.store') }}" method="POST">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">

    <div class="form-group @if($errors->has('title')) has-error @endif">
     <label for="title-field">Title</label>
     <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}" required>
     @if($errors->has("title"))
     <span class="help-block">{{ $errors->first("title") }}</span>
     @endif
   </div>
   <div class="form-group @if($errors->has('description')) has-error @endif">
     <label for="description-field">Description</label>
     <textarea class="form-control" id="description-field" rows="3" name="description">{{ old("description") }}</textarea>
     @if($errors->has("description"))
     <span class="help-block">{{ $errors->first("description") }}</span>
     @endif
   </div>
   <div class="form-group @if($errors->has('redirect')) has-error @endif">
     <label for="redirect-field">Redirection Location</label>
     <input type="text" id="redirect-field" name="redirect" class="form-control" value="{{ old("redirect") }}" required>
     <span class="help-block">Where will this form redirect once submitted?</span>
     @if($errors->has("redirect"))
     <span class="help-block">{{ $errors->first("redirect") }}</span>
     @endif
   </div>
   <div class="form-group @if($errors->has('email_to')) has-error @endif">
     <label for="email_to-field">Email the enquires to who?</label>
     <input type="text" id="email_to-field" name="email_to" class="form-control" value="{{ old("email_to") }}"/>
     <span class="help-block">Who will this email sent to? Comma separated for multiple emails.</span>
     @if($errors->has("email_to"))
     <span class="help-block">{{ $errors->first("email_to") }}</span>
     @endif
   </div>
   <div class="form-group @if($errors->has('email_cc')) has-error @endif">
     <label for="email_cc-field">CC emails for enquires</label>
     <input type="text" id="email_cc-field" name="email_cc" class="form-control" value="{{ old("email_cc") }}"/>
     <span class="help-block">Who will this email cc to? Comma separated for multiple emails.</span>
     @if($errors->has("email_cc"))
     <span class="help-block">{{ $errors->first("email_cc") }}</span>
     @endif
   </div>
   <div class="form-group @if($errors->has('email_bcc')) has-error @endif">
     <label for="email_bcc-field">BCC for enquiries</label>
     <input type="text" id="email_bcc-field" name="email_bcc" class="form-control" value="{{ old("email_bcc") }}"/>
     <span class="help-block">Who will this email bcc to? Comma separated for multiple emails.</span>
     @if($errors->has("email_bcc"))
     <span class="help-block">{{ $errors->first("email_bcc") }}</span>
     @endif
   </div>
{{--  <div class="form-group @if($errors->has('displayable_on')) has-error @endif">
       <label for="displayable_on-field">Urls Displayable On</label>
       <textarea class="form-control" id="displayable_on-field" rows="3" name="displayable_on">{{ old("displayable_on") }}</textarea>
       <span class="help-block">On what URLs can this form be displayed? Can use wildcards e.g: mywebsite.com/* or a specific url e.g: mywebsite.com/example</span>
       @if($errors->has("displayable_on"))
       <span class="help-block">{{ $errors->first("displayable_on") }}</span>
       @endif
     </div> --}}
   <div class="form-group @if($errors->has('fields')) has-error @endif">
     <label for="fields-field">Form Fields</label>
     @foreach($fields as $field)
     <div class="checkbox">
      <label>
        <input type="checkbox" name="fields[]" value="{{ $field->id }}" {{ $field->field_type == 'submit' ? 'checked=checked' : ''}}> {{ $field->field_label }}
      </label>
    </div>
    @endforeach
    <span class="help-block">Select which fields should display on this form.</span>
    @if($errors->has("fields"))
    <span class="help-block">{{ $errors->first("fields") }}</span>
    @endif
  </div>
  <div class="well well-sm">
    @if(count($fields))
    <button type="submit" class="btn btn-primary">Create</button>
    @endif
    <a class="btn btn-link pull-right" href="{{ route('lead_forms.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
  </div>
</form>

</div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $('.date-picker').datepicker({
  });
</script>
@endsection

resources/views/lead_forms/edit.blade.php
@extends('spark::layouts.app-inner')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
  <h3><i class="glyphicon glyphicon-edit"></i> Edit Lead Form  - {{$lead_form->title}}</h3>
</div>
@endsection

@section('content')
@include('error')

<div class="row">
  <div class="col-md-12">

    <form action="{{ route('lead_forms.update', $lead_form->id) }}" method="POST">
      <input type="hidden" name="_method" value="PUT">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="form-group @if($errors->has('title')) has-error @endif">
       <label for="title-field">Title</label>
       <input type="text" id="title-field" name="title" class="form-control" value="{{ is_null(old("title")) ? $lead_form->title : old("title") }}"/>
       @if($errors->has("title"))
       <span class="help-block">{{ $errors->first("title") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('description')) has-error @endif">
       <label for="description-field">Description</label>
       <textarea class="form-control" id="description-field" rows="3" name="description">{{ is_null(old("description")) ? $lead_form->description : old("description") }}</textarea>
       @if($errors->has("description"))
       <span class="help-block">{{ $errors->first("description") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('redirect')) has-error @endif">
       <label for="redirect-field">Redirection Location</label>
       <input type="text" id="redirect-field" name="redirect" class="form-control" value="{{ is_null(old("redirect")) ? $lead_form->redirect : old("redirect") }}"/>
       <span class="help-block">Where will this form redirect once submitted?</span>
       @if($errors->has("redirect"))
       <span class="help-block">{{ $errors->first("redirect") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('email_to')) has-error @endif">
       <label for="email_to-field">Email the enquires to who?</label>
       <input type="text" id="email_to-field" name="email_to" class="form-control" value="{{ is_null(old("email_to")) ? $lead_form->email_to : old("email_to") }}"/>
       <span class="help-block">Who will this email sent to? Comma separated for multiple emails.</span>
       @if($errors->has("email_to"))
       <span class="help-block">{{ $errors->first("email_to") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('email_cc')) has-error @endif">
       <label for="email_cc-field">CC emails for enquires</label>
       <input type="text" id="email_cc-field" name="email_cc" class="form-control" value="{{ is_null(old("email_cc")) ? $lead_form->email_cc : old("email_cc") }}"/>
       <span class="help-block">Who will this email cc to? Comma separated for multiple emails.</span>
       @if($errors->has("email_cc"))
       <span class="help-block">{{ $errors->first("email_cc") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('email_bcc')) has-error @endif">
       <label for="email_bcc-field">BCC for enquiries</label>
       <input type="text" id="email_bcc-field" name="email_bcc" class="form-control" value="{{ is_null(old("email_bcc")) ? $lead_form->email_bcc : old("email_bcc") }}"/>
       <span class="help-block">Who will this email bcc to? Comma separated for multiple emails.</span>
       @if($errors->has("email_bcc"))
       <span class="help-block">{{ $errors->first("email_bcc") }}</span>
       @endif
     </div>
     <div class="form-group @if($errors->has('fields')) has-error @endif">
       <label for="fields-field">Form Fields</label>
       @foreach($fields as $delta => $field)
       <div class="checkbox">
        <label>
          <input type="checkbox" name="fields[]" value="{{ $field->id }}" {{ $lead_form->fields->contains($field->id) || (old("fields{$delta}")) ? 'checked="checked"' : '' }}> {{ $field->field_label }}
        </label>
      </div>
      @endforeach
      <span class="help-block">Select which fields should display on this form.</span>
      @if($errors->has("fields"))
      <span class="help-block">{{ $errors->first("fields") }}</span>
      @endif
    </div>
    <div class="form-group @if($errors->has('displayable_on')) has-error @endif">
     <label for="displayable_on-field">Urls Displayable On</label>
     <textarea class="form-control" id="displayable_on-field" rows="3" name="displayable_on">{{ is_null(old("displayable_on")) ? $lead_form->displayable_on : old("displayable_on") }}</textarea>
     <span class="help-block">On what URLs can this form be displayed? Can use wildcards e.g: mywebsite.com/* or a specific url e.g: mywebsite.com/example</span>
     @if($errors->has("displayable_on"))
     <span class="help-block">{{ $errors->first("displayable_on") }}</span>
     @endif
   </div>
   <div class="well well-sm">
    <button type="submit" class="btn btn-primary">Save</button>
    <a class="btn btn-link pull-right" href="{{ route('lead_forms.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
  </div>
</form>

</div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $('.date-picker').datepicker({
  });
</script>
@endsection

resources/views/lead_forms/index.blade.php
@extends('spark::layouts.app-inner')
@section('header')
<div class="page-header clearfix">
  <h1>
    <i class="glyphicon glyphicon-align-justify"></i> Forms
    <a class="btn btn-success pull-right" href="{{ route('lead_forms.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
  </h1>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    @if($lead_forms->count())
    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Description</th>
          {{-- <th>URLs</th> --}}
          <th>Redirect</th>
          <th>Main Email</th>
          <th class="text-right">OPTIONS</th>
        </tr>
      </thead>
      <tbody>
        @foreach($lead_forms as $lead_form)
        <tr>
          <td>{{$lead_form->id}}</td>
          <td>{{$lead_form->title}}</td>
          <td>{{$lead_form->description}}</td>
          <td>{{$lead_form->redirect}}</td>
          <td>{{$lead_form->email_to}}</td>
          {{-- <td>{{$lead_form->displayable_on}}</td> --}}
          <td class="text-right">
            {{-- <a class="btn btn-xs btn-primary" href="{{ route('lead_forms.show', $lead_form->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a> --}}
            <a class="btn btn-xs btn-warning" href="{{ route('lead_forms.edit', $lead_form->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
            <a class="btn btn-xs btn-info" href="{{ url('render/form', $lead_form->id)}}" data-toggle="modal" data-target="#htmlRender"><i class="glyphicon glyphicon-edit"></i> Generate HTML</a>
            <form action="{{ route('lead_forms.destroy', $lead_form->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    {!! $lead_forms->render() !!}
    @else
    <h3 class="text-center alert alert-info">There are no lead forms yet.</h3>
    @endif
  </div>
</div>

<div class="modal fade" id="htmlRender" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>
@endsection
@section('scripts')
<script>
  (function($){
    $('.modal').on('hide.bs.modal', function (e) {
      var modalData = $(this).data('bs.modal');
      // Destroy modal if has remote source – don't want to destroy modals with static content.
      if (modalData && modalData.options.remote) {
        // Destroy component. Next time new component is created and loads fresh content
        $(this).removeData('bs.modal');
        // Also clear loaded content, otherwise it would flash before new one is loaded.
        $(this).find(".modal-content").empty();
      }
    });
  })(jQuery)
</script>
@endsection

resources/views/lead_forms/show.blade.php
@extends('spark::layouts.app-inner')
@section('header')
<div class="page-header">
  <h1>LeadForms / Show #{{$lead_form->id}}</h1>
  <form action="{{ route('lead_forms.destroy', $lead_form->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="btn-group pull-right" role="group" aria-label="...">
      <a class="btn btn-warning btn-group" role="group" href="{{ route('lead_forms.edit', $lead_form->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
      <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
    </div>
  </form>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    <form action="#">
      <div class="form-group">
        <label for="nome">ID</label>
        <p class="form-control-static"></p>
      </div>
      <div class="form-group">
       <label for="title">TITLE</label>
       <p class="form-control-static">{{$lead_form->title}}</p>
     </div>
     <div class="form-group">
       <label for="description">DESCRIPTION</label>
       <p class="form-control-static">{{$lead_form->description}}</p>
     </div>
   </form>
   <a class="btn btn-link" href="{{ route('lead_forms.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
 </div>
</div>
@endsection