routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'WelcomeController@show');

Route::get('home', 'HomeController@show');

Route::resource("leads", 'LeadController');
Route::resource("lead_status", "LeadStatusController");
Route::resource("lead_forms", "LeadFormController");
Route::resource("lead_form_fields", "LeadFormFieldController");
Route::resource("field_values", "FieldValueController");

Route::get('render/form/{form}', 'FormRenderController@view');
Route::get('render/field/{type}', 'FormFieldRenderController@view');

Route::get('email/submission/{submission}', 'SendEmailsController@sendSubmission');
Route::post('leadform/settings/{form}', 'FormSettingsController@view');

Route::get('shopify', 'ShopifyController@index');
Route::get('shopify/register', 'ShopifyOAuthController@register');
Route::get('shopify/start_auth', 'ShopifyOAuthController@startAuth');
Route::get('shopify/authorise', 'ShopifyOAuthController@authorise');
Route::get('shopify/settings', 'ShopifyController@settings');
Route::get('shopify/help', 'ShopifyController@help');

app/Lead.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;

class Lead extends Model
{
  use HasTeamScope;

  public static function existingLead($email, LeadForm $form){
    $existing = self::where([
      'email' => $email,
      'lead_form_id' => $form->id,
      ])->first();

    if(!$existing){
      $existing = new self();
      $existing->email = $email;
      $existing->lead_form_id = $form->id;
      $existing->team_id = $form->team_id;
      $existing->save();
    }

    return $existing;
  }

  public function status(){
    return $this->belongsTo(LeadStatus::class);
  }

  public function leadForm(){
    return $this->belongsTo(LeadForm::class);
  }

  public function form(){
    return $this->leadForm()->first();
  }

  public function submissions(){
    return $this->hasMany(Submission::class);
  }
  public function values(){
    return $this->hasManyThrough(FieldValue::class, Submission::class);
  }

  public function teamSubmissions(){
    return $this->submissions()->team()->get();
  }

  public function getDisplayDateAttribute($value){
    return $this->created_at->toDayDateTimeString();
  }

  public function path(){
    return url("leads/{$this->id}");
  }
  public function fields(){
    return $this->form()->fields->sortBy('weight')->filter(function($field){
      $doNotDisplayFields = ['submit', 'email'];
      return !in_array($field->field_type, $doNotDisplayFields);
    });
  }
}

app/LeadForm.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use App\Mail\NewEnquiry;
use Form;
use Mail;
use Exception;

class LeadForm extends Model
{
  use HasTeamScope;

  public $fillable = [
  'title',
  'redirect',
  'description',
  'displayable_on',
  'email_to',
  'email_cc',
  'email_bcc',
  ];

  /**
   * Syncs up the fields on lead form.
   *
   * You cannot run this until the model has been saved.
   *
   * @param  array  $field_ids
   * @return [void]
   */
  public function saveFields(array $field_ids){
    if(empty($field_ids)){
      return;
    }
    $this->createPageRefererField();
    $this->fields()->sync($field_ids);
  }

  public function addField(LeadFormField $field){
    $this->fields()->save($field);
  }

  public function leads(){
    return $this->hasMany(Lead::class);
  }

  public function submission(){
    return $this->hasMany(Submission::class);
  }

  public function ownerTeam(){
    return $this->belongsTo(Team::class, 'team_id');
  }

  public function owner(){
    return $this->belongsTo(Team::class, 'team_id')->first()->owner;
  }

  public function fields(){
    return $this->belongsToMany(LeadFormField::class, 'lead_form_lead_form_fields', 'form_id', 'form_field_id')
    ->withPivot('weight');
  }

  public function teamFields(){
    return $this->fields()->team();
  }

  public function emailField(){
    return $this->fields()->where('field_type', 'email')->first();
  }

  public function emailFieldInRequest(Request $request){
    $emailField = $this->emailField();

    if(!$emailField){
      abort(422, 'Your form does not have an email field, which is required.');
    }

    if(!$request->has($emailField->machine_name)){
      abort(422, 'Your submission does have an email value.');
    }

    return $request->{$emailField->machine_name};
  }

  public function getDisplayDateAttribute($value){
    return $this->updated_at->diffForHumans();
  }

  public function path(){
    return url("lead_forms/{$this->id}/edit");
  }

  public function mail(NewEnquiry $enquiry_mail){
    $to = $this->email_to ?: $this->owner()->email;
    $cc = explode(',', $this->email_cc);
    $bcc = explode(',', $this->email_bcc);
    $mail = Mail::to($to);

    if($this->email_cc){
      $mail->cc($cc);
    }

    if($this->email_bcc){
      $mail->bcc($bcc);
    }

    $mail->send($enquiry_mail);
  }

  public function buildHTML(){
    //TODO: test if CSRF can come from another domain
    $html[] = Form::open(['url' => $this->getFormActionURL()]);

    foreach($this->fields->sortBy('weight') as $field){
      list($label, $field) = $this->renderHTMLFactory($field->field_type)->render($field);

      //TODO: Add an option for bootstrap styling.
      if($label->toHtml() . $field->toHtml()){
        $html[] = '<div class="form-group form-item">';
        $html[] = $label->toHtml() . $field->toHtml();
        $html[] = '</div>';
      }
    }

    $html[] = '<!--Do not remove this, it is spam detection-->';
    $html[] = Form::hidden('super_required_field');
    $html[] = Form::hidden('redirect', $this->redirect);
    $html[] = Form::hidden('form_id', $this->id);
    $html[] = Form::close();

    return $html;
  }

  protected function renderHTMLFactory($type){
    $class = 'App\Autocoda\FormHtml\\' . ucfirst($type) . 'Field';

    return app($class);
  }

  protected function getFormActionURL(){
    return url('submit');
  }

  protected function createPageRefererField(){
    $refererField = LeadFormField::where('field_type', 'page_referer')->first();

    if($refererField){
      return;
    }

    $refererField = new LeadFormField;
    $refererField->machine_name = 'page_referer';
    $refererField->field_type = 'page_referer';
    $refererField->field_label = 'Page Submitted From';
    $refererField->save();
  }
}

app/Http/Controllers/LeadController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Lead;
use Illuminate\Http\Request;

class LeadController extends Controller {

  /**
   * Create a new controller instance.
   *
   * @return void
   */
  public function __construct()
  {
    $this->middleware('auth');
  }

  /**
   * Display a listing of the resource.
   *
   * @return Response
   */
  public function index()
  {
    $leads = Lead::team()->orderBy('id', 'desc')->paginate(10);

    return view('leads.index', compact('leads'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return Responsek
   */
  public function create()
  {
    return view('leads.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param Request $request
   * @return Response
   */
  public function store(Request $request)
  {
    $lead = new Lead();

    $lead->name = $request->input("name");
    $lead->subject = $request->input("subject");
    $lead->enquiry = $request->input("enquiry");

    $lead->save();

    return redirect()->route('leads.index')->with('message', 'Item created successfully.');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function show($id)
  {
    $lead = Lead::findOrFail($id);

    return view('leads.show', compact('lead'));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return Response
   */
  public function edit($id)
  {
    $lead = Lead::findOrFail($id);

    return view('leads.edit', compact('lead'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  int  $id
   * @param Request $request
   * @return Response
   */
  public function update(Request $request, $id)
  {
    $lead = Lead::findOrFail($id);

    $lead->name = $request->input("name");
    $lead->subject = $request->input("subject");
    $lead->enquiry = $request->input("enquiry");

    $lead->save();

    return redirect()->route('leads.index')->with('message', 'Item updated successfully.');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return Response
   */
  public function destroy($id)
  {
    $lead = Lead::findOrFail($id);
    $lead->values()->delete();
    $lead->submissions()->delete();
    $lead->delete();

    return redirect()->route('leads.index')->with('message', 'Item deleted successfully.');
  }

}

resources/views/leads/create.blade.php
@extends('spark::layouts.app-inner')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
  <h1><i class="glyphicon glyphicon-plus"></i> Create a new Lead</h1>
</div>
@endsection
@section('content')
@include('error')

<div class="row">
  <div class="col-md-12">
    <form action="{{ route('leads.store') }}" method="POST">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="form-group @if($errors->has('email')) has-error @endif">
        <label for="email-field">Email</label>
        <input type="email" id="email-field" name="email" class="form-control" value="{{ old("email") }}"/>
        @if($errors->has("email"))
        <span class="help-block">{{ $errors->first("email") }}</span>
        @endif
      </div>
      {{-- Need form id here --}}
      <div class="well well-sm">
        <button type="submit" class="btn btn-primary">Create</button>
        <a class="btn btn-link pull-right" href="{{ route('leads.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
      </div>
    </form>
  </div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $('.date-picker').datepicker({
  });
</script>
@endsection

resources/views/leads/edit.blade.php
@extends('spark::layouts.app-inner')
@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
<div class="page-header">
  <h1><i class="glyphicon glyphicon-edit"></i> Edit Lead #{{$lead->id}}</h1>
</div>
@endsection

@section('content')
@include('error')

<div class="row">
  <div class="col-md-12">
    <form action="{{ route('leads.update', $lead->id) }}" method="POST">
      <input type="hidden" name="_method" value="PUT">
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      <div class="form-group @if($errors->has('email')) has-error @endif">
       <label for="name-field">Email</label>
       <input type="email" id="name-field" name="name" class="form-control" value="{{ is_null(old("email")) ? $lead->email : old("email") }}"/>
       @if($errors->has("email"))
       <span class="help-block">{{ $errors->first("email") }}</span>
       @endif
     </div>
     <div class="well well-sm">
      <button type="submit" class="btn btn-primary">Save</button>
      <a class="btn btn-link pull-right" href="{{ route('leads.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
    </div>
  </form>

</div>
</div>
@endsection
@section('scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
<script>
  $('.date-picker').datepicker({
  });
</script>
@endsection

resources/views/leads/index.blade.php
@extends('spark::layouts.app-inner')
@section('header')
<div class="page-header clearfix">
  <h1>
    <i class="glyphicon glyphicon-align-justify"></i> Leads
    {{-- <a class="btn btn-success pull-right" href="{{ route('leads.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a> --}}
  </h1>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    @if($leads->count())
    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Email</th>
          <th>Form</th>
          <th># Submissions</th>
          <th>Progression</th>
          {{-- <th>Url</th> --}}
          <th class="text-right">OPTIONS</th>
        </tr>
      </thead>
      <tbody>
        @foreach($leads as $lead)
        <tr>
          <td>{{ $lead->id }}</td>
          <td>{{ $lead->email }}</td>
          <td>{{ $lead->form()->title }}</td>
          <td>{{ count($lead->submissions) }}</td>
          <td>TODO</td>
          {{-- <td>TODO</td> --}}
          <td class="text-right">
            <a class="btn btn-xs btn-primary" href="{{ route('leads.show', $lead->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
            <a class="btn btn-xs btn-warning" href="{{ route('leads.edit', $lead->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
            <form action="{{ route('leads.destroy', $lead->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
              <input type="hidden" name="_method" value="DELETE">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              {{-- <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button> --}}
            </form>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    {!! $leads->render() !!}
    @else
    <h3 class="text-center alert alert-info">There are no leads yet.</h3>
    @endif
  </div>
</div>
@endsection

resources/views/leads/lead-table.blade.php
<table class="table">
  <thead>
    <tr>
      @foreach($lead->fields() as $field)
      <th>{{ $field->field_label }}</th>
      @endforeach
      <th>Submitted</th>
    </tr>
  </thead>
  <tbody>
    @foreach($lead->teamSubmissions() as $submission)
    <tr>
      @foreach($lead->fields() as $field)
      <td>
        @if(is_array($submission->value($field->id)))
        <ul>
          @foreach($submission->value($field->id) as $list_item)
          <li>{{ $list_item }}</li>
          @endforeach
        </ul>
        @else
        {{ $submission->value($field->id) }}
        @endif
      </td>
      @endforeach
      <td>{{ $submission->created_at->diffForHumans() }}</td>
    </tr>
    @endforeach
  </tbody>
</table>

resources/views/leads/show.blade.php
@extends('spark::layouts.app-inner')
@section('header')
<div class="page-header">
  <h1>Lead #{{$lead->id}}</h1>
  <form action="{{ route('leads.destroy', $lead->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <div class="btn-group pull-right" role="group" aria-label="...">
      <a class="btn btn-warning btn-group" role="group" href="{{ route('leads.edit', $lead->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
      <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
    </div>
  </form>
</div>
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    <form action="#">
      <div class="form-group">
        <label for="nome">ID</label>
        <p class="form-control-static">{{$lead->id}}</p>
      </div>
      <div class="form-group">
        <label for="name">Email</label>
        <p class="form-control-static">{{$lead->email}}</p>
      </div>
      <h3>Submissions</h3>
      @include ('leads.lead-table')
{{--       <div class="form-group">
        <label for="subject">SUBJECT</label>
        <p class="form-control-static">{{$lead->subject}}</p>
      </div>
      <div class="form-group">
        <label for="enquiry">ENQUIRY</label>
        <p class="form-control-static">{{$lead->enquiry}}</p>
      </div> --}}
    </form>
    <a class="btn btn-link" href="{{ route('leads.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
  </div>
</div>

@endsection